@echo off
set NODE_TLS_REJECT_UNAUTHORIZED=0

echo Adding NEXT_PUBLIC_SUPABASE_ANON_KEY...
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobGx4Z2h1ZWhmZXFrcHFsdnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5NzYwMjMsImV4cCI6MjA5MzU1MjAyM30.pi92iDnJJqLUeh7cPP7LPNyu8uQ4zv1KRofFJOuj7AM | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production

echo.
echo Adding SUPABASE_SERVICE_ROLE_KEY...
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobGx4Z2h1ZWhmZXFrcHFsdnBtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Nzk3NjAyMywiZXhwIjoyMDkzNTUyMDIzfQ.BIeLF5upkTHgabv-oiw21mbGjtZZj_Xar4FEFWVrRtg | vercel env add SUPABASE_SERVICE_ROLE_KEY production

echo.
echo Done! Environment variables added.
echo Now run: vercel --prod
pause
